package:
    name: estoktp
    version: "1.10.1"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
    host:
        - blas
        - openblas # [linux]
    run:
        - blas
        - openblas # [linux]
        - mess
