# cmd: conda build . -c pacchem
package:
    name: estoktp
    version: "1.10.4"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
    run:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - mess
