version: 2
jobs:
    build:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes build-essential
                    conda env create -f environment.yml
            - run:
                name: Build the code
                command: |
                    source activate estoktp-env
                    bash debug/build.sh
            - run:
                name: Test the code
                command: |
                    apt-get install --yes bc    # for the frequency checker
                    source activate estoktp-env
                    . debug/fake-install.sh
                    tar -zxvf examples/h4on.tgz
                    cd h4on/
                    estoktp.x
                    bash check_frequencies.sh
workflows:
    version: 2
    build-all:
        jobs:
            - build
